### ISSUE TITLE
Cannot install mingw gcc

### ISSUE THREAD

**Issue by kelesi** [aboood40091/sm64-port#14]
I followed the tutorial and installed devkitPro on Windows, setup Fling repo, and installed all the dependencies.
I am unable to install mingw-w64-i686-gcc.

```
MINGW64 ~
$ pacman -S mingw-w64-i686-gcc
error: target not found: mingw-w64-i686-gcc
```

Thanks for any advice.

**Comment by aboood40091** [comment]
I am assuming you are using the msys2 included with the devkitPro Windows Installer.
Don't use that; use the official msys2 instead (you will have to manually install devkitPro on it).
The official discord server, linked in the README, has instructions on doing that.

**Comment by kelesi** [comment]
Yes, I already figured it out the hard way.
It worked using the discord instructions.
The problem is the README links to general WiiU development instructions
where it says to install devkitPro. Maybe the README could be updated with
proper instructions for WiiU and Windows?
Next time I will rather try to compile under WSL2 or standalone Linux.
Thanks.


Dňa so 12. 9. 2020, 12:01 AboodXD <notifications@github.com> napísal(a):
