### ISSUE TITLE
60 FPS patch failed to apply

### ISSUE THREAD

**Issue by scout213** [aboood40091/sm64-port#17]
When running ./tools/apply_patch.sh enhancements/60fps.patch the following errors occur:

Do you wish to apply the patch 'enhancements/60fps.patch'? [Y/N] y
patching file include/types.h
Hunk #1 succeeded at 117 (offset -1 lines).
Hunk #2 FAILED at 132.
Hunk #3 succeeded at 246 (offset -1 lines).
1 out of 3 hunks FAILED -- saving rejects to file include/types.h.rej
patching file src/engine/graph_node.h
patching file src/engine/surface_collision.c
patching file src/engine/surface_load.c
Hunk #2 succeeded at 384 (offset 24 lines).
patching file src/game/camera.c
patching file src/game/camera.h
patching file src/game/envfx_bubbles.c
patching file src/game/envfx_snow.c
patching file src/game/envfx_snow.h
patching file src/game/hud.c
patching file src/game/ingame_menu.c
patching file src/game/level_geo.c
patching file src/game/object_helpers.c
Hunk #1 succeeded at 1549 (offset -5 lines).
patching file src/game/paintings.c
patching file src/game/rendering_graph_node.c
Hunk #19 FAILED at 675.
Hunk #24 FAILED at 891.
Hunk #25 FAILED at 1004.
Hunk #31 succeeded at 1135 with fuzz 1.
Hunk #33 succeeded at 1280 with fuzz 2.
Hunk #34 succeeded at 1295 (offset 4 lines).
Hunk #35 succeeded at 1308 (offset 4 lines).
3 out of 35 hunks FAILED -- saving rejects to file src/game/rendering_graph_node.c.rej
patching file src/game/screen_transition.c
Hunk #4 FAILED at 236.
1 out of 4 hunks FAILED -- saving rejects to file src/game/screen_transition.c.rej
patching file src/menu/intro_geo.c
patching file src/pc/gfx/gfx_dxgi.cpp
patching file src/pc/gfx/gfx_glx.c
patching file src/pc/gfx/gfx_sdl2.c
patching file src/pc/gfx/gfx_whb_window.c
Hunk #1 succeeded at 55 (offset 3 lines).
patching file src/pc/pc_main.c
Hunk #1 succeeded at 79 (offset 1 line).
Hunk #2 succeeded at 117 (offset 1 line).

**Comment by V10lator** [comment]
The patch is completely broken. Even if you fix the applying the game either flickers or crashes on entering of the first painting.

**Comment by V10lator** [comment]
Workaround:
1) Use this patch: https://raw.githubusercontent.com/sm64-port/sm64-port/6117ab9e4ced81bcb5c1fd31d353f238da87e05e/enhancements/60fps.patch
2) Remove `GX2SetSwapInterval(2);` from `src/pc/gfx/gfx_whb_window.c` (line 60)

**Comment by aboood40091** [comment]
I keep forgetting to check this out since I keep getting sidetracked by other projects.
