### ISSUE TITLE
KPADShutdown not defined

### ISSUE THREAD

**Issue by amg-12** [aboood40091/sm64-port#24]
When compiling for Wii U, I get this error:

```bash
Compiling: src/pc/gfx/gfx_gx2_window.cpp -> build/eu_wiiu/src/pc/gfx/gfx_gx2_window.o
src/pc/gfx/gfx_gx2_window.cpp: In function 'void gfx_gx2_window_exit_callback()':
src/pc/gfx/gfx_gx2_window.cpp:80:5: error: 'KPADShutdown' was not declared in this scope; did you mean 'WPADShutdown'?
   80 |     KPADShutdown();
      |     ^~~~~~~~~~~~
      |     WPADShutdown
Makefile:905: recipe for target 'build/eu_wiiu/src/pc/gfx/gfx_gx2_window.o' failed
make: *** [build/eu_wiiu/src/pc/gfx/gfx_gx2_window.o] Error 1
```

Changing KPADShutdown to WPADShutdown solves the problem and the game compiles and runs fine, but I'm not sure if I've introduced bugs to the controls by doing that.

**Comment by aboood40091** [comment]
You should update wut as a recent commit introduced that function.
Another fix would be to manually declare the function in the same file that gives the error.
